run-name: Publish browser using devcontainer:${{ inputs.image_tag }}

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Devcontainer image tag"
        required: false
        type: string
        default: "latest"

  workflow_call:
    inputs:
      image_tag:
        description: "Devcontainer image tag"
        required: false
        type: string
        default: "latest"

permissions:
  contents: read
  packages: read

jobs:
  publish:
    uses: ./.github/workflows/devcontainer.yml
    with:
      image_tag: ${{ inputs.image_tag }}
      push: false
      run_cmd: dotnet publish Foreweather.Browser/Foreweather.Browser.csproj -c Release