name: Publish browser release

run-name: Publish browser using devcontainer:${{ inputs.image_tag }}

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Devcontainer image tag"
        required: false
        type: string
        default: "latest"

  workflow_call:
    inputs:
      image_tag:
        description: "Devcontainer image tag"
        required: false
        type: string
        default: "latest"

permissions:
  contents: read
  packages: read

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}/devcontainer

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish browser inside devcontainer
        uses: devcontainers/ci@v0.3
        with:
          imageName: ${{ env.IMAGE_NAME }}
          imageTag: ${{ inputs.image_tag }}
          cacheFrom: ${{ env.IMAGE_NAME }}:${{ inputs.image_tag }}
          push: never
          runCmd: dotnet publish src/Foreweather.Browser -c Release